services:
  spring:
    image: 'user-service-emi:1'
    ports:
      - '8002:8002'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/userDB'
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=userDB'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'MYSQL_USER=user'
    ports:
      - '3306:3306'