services:
  spring:
    image: 'user-service-emi:1'
    ports:
      - '8003:8003'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/user'
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=user'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'