services:
  spring:
    image: 'user-service-emi:1'
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - '8083:8080'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/user'
  mysql:
    image: 'mysql:latest'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      - 'MYSQL_DATABASE=user'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'