apiVersion: v1
kind: PersistentVolume
metadata:
  name: imageservice-mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/imageservice-mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: imageservice-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
      