apiVersion: v1
kind: Secret
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: mysql:latest
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  