apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: authservice
          image: ghcr.io/chatgut/authservice2:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: authservice-mysql:3306/authservice-mysql
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: authservice-secret
                  key: db-user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: authservice-secret
                  key: db-pass

      